project:
  type: website

website:
  title: "We charleston the world"
  navbar:
    title: "We charleston the world"
    right:
      - icon: github
        href: https://github.com/shaenzi
      - icon: mastodon
        href: https://mas.to/@sarahaenzi
      - text: Main Website
        href: https://www.sarahaenzi.com/
format:
  html:
    theme: darkly
    css: styles.css



